
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    initialization-mode: ALWAYS
